name: ci
# only deploy site from master branch
on: push

# TODO split into several jobs for speed
jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      # only install dependencies
      # https://github.com/cypress-io/github-action
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Check links ⚓️
        run: npm run check:links

      - name: Set Cypress version 🎁
        id: cypress
        run: echo "::set-output name=version::$(node ./src/print-cypress-version)"

      - name: Print Cypress version 🖨
        run: echo "Cypress version is ${{ steps.cypress.outputs.version }}"

      - name: Build site 🏗
        run: npm run docs:build

      - name: Export Markdown specs 🖨
        run: node ./md-to-js http://localhost:5000/cypress-examples/${{ steps.cypress.outputs.version }}

      - name: Catch stray .only tests 🚦
        run: npm run stop-only

      # we "simulate" Run All Specs button in Test Runner GUI
      # by concatenating all extracted specs into a single one
      # to be included in the test run
      - name: Create Run All Spec 🏗
        run: cat docs/**/*.js > docs/run-all-specs.js

      - name: Save built folders
        uses: actions/upload-artifact@v2
        with:
          name: install-and-build
          path: |
            ~/.cache/Cypress
            node_modules
            public

  test-markdown:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Download built folders
        uses: actions/download-artifact@v2
        with:
          name: install-and-build

      # run all tests straight from Markdown files
      # using Cypress GH action
      # https://github.com/cypress-io/github-action
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          group: 1. Markdown
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.recordKey }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: See any changed files 👀
        run: git status

      # if there are any updated PNG images, commit and push them
      - name: Commit any changed images 💾
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated screenshots
          branch: master
          file_pattern: '*.png'
  # test:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     # https://github.com/actions/checkout
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v2
  #     - name: Test built site 🧪
  #       uses: cypress-io/github-action@v2
  #       with:
  #         # we have already installed all dependencies above
  #         install: false
  #         start: npm run serve
  #         config-file: cypress-dist.json
  #         record: true
  #         group: 2. JavaScript specs
  #       env:
  #         CYPRESS_RECORD_KEY: ${{ secrets.recordKey }}
  #         # pass GitHub token to allow accurately detecting a build vs a re-run build
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     # if something has failed, let's store screenshots
  #     - uses: actions/upload-artifact@v1
  #       if: failure()
  #       with:
  #         name: cypress-dist-screenshots
  #         path: cypress/screenshots
  #     # https://github.com/marketplace/actions/github-pages-action
  #     - name: Deploy 🚀
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./public/cypress-examples/${{ steps.cypress.outputs.version }}
  #         destination_dir: ${{ steps.cypress.outputs.version }}
  #     - name: Export page redirects ↗️
  #       run: node ./md-to-redirects https://glebbahmutov.com/cypress-examples/${{ steps.cypress.outputs.version }}
  #     # deploy the redirect pages that point every top level
  #     # HTML page the Cypress Test Runner might load to the corresponding
  #     # page under the latest version
  #     - name: Deploy redirects 🚀
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         # make sure to preserve the existing files
  #         keep_files: true
  #         publish_dir: ./redirects
  #         destination_dir: .
