name: ci
# only deploy site from master branch
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # run all tests straight from Markdown files
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          config: video=false

      # if there are any updated PNG images, commit and push them
      - name: Commit any changed images 💾
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated screenshots
          branch: main
          file_pattern: '*.png'

      # if something has failed, let's store screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Check links ⚓️
        run: npm run check:links

      - name: Set Cypress version 🎁
        id: cypress
        run: echo "::set-output name=version::$(node ./src/print-cypress-version)"

      - name: Print Cypress version 🖨
        run: echo "Cypress version is ${{ steps.cypress.outputs.version }}"

      - name: Build site 🏗
        run: npm run docs:build

      - name: Export Markdown specs 🖨
        run: node ./md-to-js http://localhost:5000/cypress-examples/${{ steps.cypress.outputs.version }}

      - name: Catch stray .only tests 🚦
        run: npm run stop-only

      # we "simulate" Run All Specs button in Test Runner GUI
      # by concatenating all extracted specs into a single one
      # to be included in the test run
      - name: Create Run All Spec 🏗
        run: cat docs/**/*.js > docs/run-all-specs.js

      - name: Test built site 🧪
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: npm run serve
          config-file: cypress-dist.json

      # if something has failed, let's store screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-dist-screenshots
          path: cypress/screenshots

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/cypress-examples/${{ steps.cypress.outputs.version }}
          destination_dir: ${{ steps.cypress.outputs.version }}
